import type { Metadata } from 'next';
import { Kelly_Slab } from 'next/font/google';

import TanStackProvider from '@/providers/TanStackProvider';
import AuthProvider from '@/context/auth/AuthProvider';

import '../styles/globals.css';

const kelly = Kelly_Slab({ subsets: ['latin'], weight: ['400'] });

export const metadata: Metadata = {
	title: 'App Sorteos',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body
				className={`${kelly.className} bg-[#2E2D54]`}
				suppressHydrationWarning={true}>
				<TanStackProvider>
					<AuthProvider>{children}</AuthProvider>
				</TanStackProvider>
			</body>
		</html>
	);
}
