import type { Metadata } from 'next';
import { Kelly_Slab } from 'next/font/google';
import '../styles/globals.css';

const kelly = Kelly_Slab({ subsets: ['latin'], weight: ['400'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={kelly.className}>{children}</body>
		</html>
	);
}
